name: CI

on: 
  push:
    branches: 
      - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'  
    - name: install npm
      run: npm install
    - name: npm build
      run: npm run build
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.3.1
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      
